### ISSUE TITLE
Resume doesn't work after a few minutes in idle

### ISSUE THREAD

**Issue by Kineon1** [svr333/audio-band#31]
Hi,
if I pause the music and come back after about 10 minutes the resume button won't work anymore. If I pause and unpause in less than 10 minutes it works normally.

I'm using 1.0.1 and mainly with Spotify. Maybe it has something to do with this resolved issue "https://github.com/svr333/audio-band/issues/22".

The issue wasn't present with 0.9.4 for me.

**Comment by svr333** [comment]
Weird, normally the fix for #22 doesn't matter seeing as it doesn't touch the SpotifyAudioSource code.

A few additional questions: 
1) When you use audioband on desktop, do you use the spotify app on your desktop? Or do you listen on your phone while controlling from audioband?

2) Is 1.0.1 the first version you used since dsafas 0.9.4? (There have been a lot of changes to the spotify audio source since then so narrowing it down could help).

3) Do you have Spotify Premium?

Thank you for the report, Ill try to recreate the bug myself and try my best to fix it

**Comment by paintballkev812** [comment]
This may be related to #30. I was noticing that the resume button would not work for me either. Never timed it, but it didn't feel like it was a super long time (definitely under 30 minutes). Some further testing showed that if I played and paused using the Spotify UI, my audio band would then work.

**Comment by svr333** [comment]
in that case it probably is related to #30, Ill do some investigating later this week

**Comment by Kineon1** [comment]
> 
> 
> Weird, normally the fix for #22 doesn't matter seeing as it doesn't touch the SpotifyAudioSource code.
> 
> A few additional questions:
> 
>     1. When you use audioband on desktop, do you use the spotify app on your desktop? Or do you listen on your phone while controlling from audioband?
> 
>     2. Is 1.0.1 the first version you used since dsafas 0.9.4? (There have been a lot of changes to the spotify audio source since then so narrowing it down could help).
> 
>     3. Do you have Spotify Premium?
> 
> 
> Thank you for the report, Ill try to recreate the bug myself and try my best to fix it

1. Only desktop
2. I think so, I just recently discovered that there is a newer version/different fork and then switched
3. Yes

For me it was probably exactly 10 minutes @paintballkev812. At 9 mins it was still possible to click the button

**Comment by svr333** [comment]
I think I know which change has affected this PR and it is not related to #30.
I'll look for a fix soon

**Comment by svr333** [comment]
> Ill try to recreate the bug myself

Was able to recreate so shouldn't be too hard to fix
