### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by erikoffereins** [svr333/audio-band#8]
When I try to use Spotify with your audioband it is opening a loginwindow.
And after a correct signin it shows the error INVALID_CLIENT: Invalid redirect URI

**Comment by svr333** [comment]
Im assuming you came from an existing build from dsafa, in that case, you have to go to the [Spotify Developer Dashboard](https://developer.spotify.com/dashboard/applications), log in, click on your existing application and click edit settings on the top right.  
Once there, go to redirect urls and make sure it maches the one on the screenshot below.
![image](https://user-images.githubusercontent.com/35664724/130042744-e80a3d67-3c72-4934-b7c8-c9aafb4446d6.png)

If you'd like the reason why this has changed, it is the following:
In order to use the latest features of Spotifys API (such as podcast support) I had to update our API Wrapper. With this came the chance that the authentication url now defaults to `http://localhost/` instead of `http://localhost:80`

**Comment by erikoffereins** [comment]
Thanks it works!
